@startuml
'https://plantuml.com/class-diagram

title Vet and Specialty View Class Diagram

left to right direction
'top to bottom direction


class VetView {

    - VetState currentState

    button_cancel_and_back(): VetState

    button_addNew_dialog(): VetState
    button_addNew_perform(): VetState
    - db_addNew(): boolean

    button_edit_dialog(): VetState
    button_update_perform(): VetState
    - db_update(): boolean

    button_delete_dialog(): VetState
    button_delete_perform(): VetState
    - db_delete(): boolean
}

class SpecialtyView {

    - SpecialtyState currentState

    button_cancel_and_back(): SpecialtyState

    button_addNew_dialog(): SpecialtyState
    button_addNew_perform(): SpecialtyState
    - db_addNew(): boolean

    button_edit_dialog(): SpecialtyState
    button_update_perform(): SpecialtyState
    - db_update(): boolean

    button_delete_dialog(): SpecialtyState
    button_delete_perform(): SpecialtyState
    - db_delete(): boolean
}

enum VetState {
    VET_LIST_EMPTY
    VET_LIST
    VET_LIST_SEARCH_RESULT
    VET_NEW
    VET_EDIT
    VET_DELETE
}

enum SpecialtyState {
    SPECIALTY_LIST_EMPTY
    SPECIALTY_LIST
    SPECIALTY_LIST_SEARCH_RESULT
    SPECIALTY_NEW
    SPECIALTY_EDIT
    SPECIALTY_DELETE
}

@enduml