@startuml

title Application Use Case Diagram

'https://plantuml.com/use-case-diagram

left to right direction
'top to bottom direction

scale 1000 width

User - (Login)
package application {
    (Login) -> (Navigation)
    (Navigation) --> (Start)
    (Navigation) --> (Info)
    (Navigation) --> (Help)
    (Navigation) --> (UserInfo)
    (Navigation) --> (Logout)
}
@enduml