@startuml

title Vetinarian State Diagram

'https://plantuml.com/state-diagram

left to right direction
' top to bottom direction

scale 1000 width

[*] --> VET_LIST

VET_LIST --> VET_NEW : button_addNew_dialog()
VET_NEW --> VET_LIST: button_addNew_perform()
VET_NEW --> VET_LIST2: button_addNew_perform() OK

VET_LIST --> VET_EDIT: button_edit_dialog()
VET_EDIT --> VET_LIST: button_update_perform()
VET_EDIT --> VET_LIST3: button_update_perform() OK

VET_LIST --> VET_DELETE: button_delete_dialog()
VET_DELETE --> VET_LIST: button_delete_perform()
VET_DELETE --> VET_LIST4: button_delete_perform() OK

VET_LIST2 --> [*]
VET_LIST3 --> [*]
VET_LIST4 --> [*]


state VET_NEW {
    VET_NEW --> VET_NEW : button_addNew_perform() not OK, invalid
}
state VET_EDIT {
    VET_EDIT --> VET_EDIT: button_update_perform() not OK, invalid
}
state VET_DELETE {
    VET_DELETE --> VET_DELETE: button_delete_perform() not OK, invalid
}


@enduml