@startuml

title PetType State Diagram
'https://plantuml.com/state-diagram

left to right direction
' top to bottom direction

scale 1000 width

[*] --> PETTYPE_LIST

PETTYPE_LIST --> PETTYPE_NEW : button_addNew()
PETTYPE_LIST --> PETTYPE_EDIT: button_edit()
PETTYPE_LIST --> PETTYPE_DELETE: button_delete()

PETTYPE_NEW --> PETTYPE_LIST: cancel_and_back()
PETTYPE_NEW --> PETTYPE_LIST2: addNew() OK

PETTYPE_EDIT --> PETTYPE_LIST: cancel_and_back()
PETTYPE_EDIT --> PETTYPE_LIST3: update() OK

PETTYPE_DELETE --> PETTYPE_LIST: cancel_and_back()
PETTYPE_DELETE --> PETTYPE_LIST4: delete() OK

PETTYPE_LIST2 --> [*]
PETTYPE_LIST3 --> [*]
PETTYPE_LIST4 --> [*]


state PETTYPE_NEW {
    PETTYPE_NEW --> PETTYPE_NEW : addNew() not OK, invalid
}
state PETTYPE_EDIT {
    PETTYPE_EDIT --> PETTYPE_EDIT: update() not OK, invalid
}
state PETTYPE_DELETE {
    PETTYPE_DELETE --> PETTYPE_DELETE: delete() not OK, invalid
}


@enduml