@startuml

title Specialty State Diagram

'https://plantuml.com/state-diagram

' left to right direction
top to bottom direction

scale 1000 width

[*] --> SPECIALTY_LIST

SPECIALTY_LIST --> SPECIALTY_NEW : button_addNew()
SPECIALTY_LIST --> SPECIALTY_EDIT: button_edit()
SPECIALTY_LIST --> SPECIALTY_DELETE: button_delete()

SPECIALTY_NEW --> SPECIALTY_LIST: cancel_and_back()
SPECIALTY_NEW --> SPECIALTY_LIST2: addNew() OK

SPECIALTY_EDIT --> SPECIALTY_LIST: cancel_and_back()
SPECIALTY_EDIT --> SPECIALTY_LIST3: update() OK

SPECIALTY_DELETE --> SPECIALTY_LIST: cancel_and_back()
SPECIALTY_DELETE --> SPECIALTY_LIST4: delete() OK

SPECIALTY_LIST2 --> [*]
SPECIALTY_LIST3 --> [*]
SPECIALTY_LIST4 --> [*]


state SPECIALTY_NEW {
    SPECIALTY_NEW --> SPECIALTY_NEW : addNew() not OK, invalid
}
state SPECIALTY_EDIT {
    SPECIALTY_EDIT --> SPECIALTY_EDIT: update() not OK, invalid
}
state SPECIALTY_DELETE {
    SPECIALTY_DELETE --> SPECIALTY_DELETE: delete() not OK, invalid
}


@enduml