@startuml
'https://plantuml.com/class-diagram


left to right direction
' top to bottom direction

scale 1000 width

package owner.oodm {

    package owner.oodm.entities {

        entity OwnerEntity {
            Long id
            String uuid
            String firstName
            String lastName
            String address
            String houseNumber
            String addressInfo
            String city
            String zipCode
            String phoneNumber
            String email
        }

        entity PetEntity {
            Long id
            String uuid
            String name
            Date dateOfBirth
        }

        entity VisitEntity {
            Long id
            String uuid
            Date dateOfVisit
            String notice
        }

        entity PetTypeEntity {
            Long id
            String uuid
            String name
        }

        OwnerEntity "one"  *--> "many"  PetEntity: pets
        PetEntity "one" *--> "many" VisitEntity: visits
        PetEntity "many"  o-->  "one" PetTypeEntity: petType

    }

    package owner.oodm.service {

        class OwnerService {
        }

        class PetService {
        }

        class VisitService {
        }

        class PetTypeService {
        }

        package owner.oodm.service.dao {

            class OwnerDao {
            }

            class PetDao {
            }

            class VisitDao {
            }

            class PetTypeDao {
            }

            OwnerDao ..> OwnerEntity
            PetDao ..> PetEntity
            PetTypeDao ..> PetTypeEntity
            VisitDao ..> VisitEntity
        }

        OwnerService o--> OwnerDao
        PetService o--> PetDao
        PetTypeService o--> PetTypeDao
        VisitService o--> VisitDao
    }

    package owner.oodm.transients {

        class OwnerDto {
            String uuid
            String firstName
            String lastName
            String address
            String houseNumber
            String addressInfo
            String city
            String zipCode
            String phoneNumber
            String email
        }

        entity PetDto {
            String uuid
            String name
            Date dateOfBirth
        }

        class PetTypeDto {
            String uuid
            String name
        }

        class VisitDto {
            String uuid
            Date dateOfVisit
            String notice
        }

        OwnerDto "one"  *--> "many"  PetDto: pets
        PetDto "one" *--> "many" VisitDto: visits
        PetDto "many"  o-->  "one" PetTypeDto: petType

        OwnerDto ..> OwnerService
        PetDto ..> PetService
        VisitDto ..> VisitService
        PetTypeDto  ..> PetTypeService
    }
}











@enduml