@startuml


title OwnerView and PetTypeView Class Diagram
'https://plantuml.com/class-diagram

left to right direction
'top to bottom direction

scale 1000 width

class OwnerView {

    - OwnerState currentState

    button_list_dialog(): OwnerState
    - load_list(): boolean

    button_owner_cancel_and_back(): OwnerState

    button_owner_details_dialog(): OwnerState
    button_owner_back_to_list(): OwnerState

    button_owner_addNew_dialog(): OwnerState
    button_owner_addNew_perform(): OwnerState
    -db_owner_addNew(): boolean

    button_owner_edit_dialog(): OwnerState
    button_owner_update_perform(): OwnerState
    - db_owner_update(): boolean

    button_owner_delete_dialog(): OwnerState
    button_owner_delete_perform(): OwnerState
    - db_owner_delete(): boolean

    button_pet_cancel_and_back(): OwnerState

    button_pet_addNew_dialog(): OwnerState
    button_pet_addNew_perform(): OwnerState
    - db_pet_addNew(): boolean

    button_pet_edit_dialog(): OwnerState
    button_pet_update_perform(): OwnerState
    - db_pet_update(): boolean

    button_pet_delete_dialog(): OwnerState
    button_pet_delete_perform(): OwnerStates
    - db_pet_delete(): boolean

    button_visit_cancel_and_back(): OwnerState

    button_visit_addNew_dialog(): OwnerState
    button_visit_addNew_perform(): OwnerState
    - db_visit_addNew(): boolean

    button_visit_edit_dialog(): OwnerState
    button_visit_update_perform(): OwnerState
   - db_visit_update(): boolean

    button_visit_delete_dialog(): OwnerState
    button_visit_delete_perform(): OwnerState
    - db_visit_delete(): boolean
}

class PetTypeView {

    - PetTypeState currentState

    button_list_dialog(): PetTypeState
    - load_list(): boolean

    button_cancel_and_back(): PetTypeState

    button_addNew_dialog(): PetTypeState
    button_addNew_perform(): PetTypeState
    - db_addNew(): boolean

    button_edit_dialog(): PetTypeState
    button_update_perform(): PetTypeState
    - db_update(): boolean

    button_delete_dialog():PetTypeState
    button_delete_perform():PetTypeState
    - db_delete(): boolean
}


enum OwnerState {
    OWNER_LIST_EMPTY
    OWNER_LIST
    OWNER_LIST_SEARCH_RESULT
    OWNER_NEW
    OWNER_DETAILS
    OWNER_EDIT
    OWNER_DELETE
    OWNER_PET_NEW
    OWNER_PET_EDIT
    OWNER_PET_DELETE
    OWNER_PET_VISIT_NEW
    OWNER_PET_VISIT_EDIT
    OWNER_PET_VISIT_DELETE
}

enum PetTypeState {
    PETTYPE_LIST_EMPTY
    PETTYPE_LIST
    PETTYPE_LIST_SEARCH_RESULT
    PETTYPE_NEW
    PETTYPE_EDIT
    PETTYPE_DELETE
}



@enduml