@startuml

title Specialty Use Case Diagram

'https://plantuml.com/use-case-diagram

left to right direction
'top to bottom direction

scale 1000 width

User - (Login)
package specialty {
    (Login) -> (Navigation)
    (Navigation) -> (Specialty.list)
    (Specialty.list) --> (Specialty.search)
    (Specialty.list) ---> (Specialty.addNew)
    (Specialty.list) ---> (Specialty.edit)
    (Specialty.list) ---> (Specialty.delete)
}
@enduml