@startuml
'https://plantuml.com/activity-diagram-beta

scale 1000 width

start
:Specialty.showList();
:Specialty.load();
:render Specialty.list page;
if(Specialty.list page) then ( Specialty.showNewForm() )
    :Specialty.showNewForm();
    :render Specialty.edit page;
else ( Specialty.cancelNew() )
    :Specialty.cancelNew();
endif
:Specialty.showList();
:Specialty.load();
:render Specialty.list page;
stop

@enduml
